/**
 * @module @vanaware/buildit/denobuild/engine
 * @description Core compilation mechanism, define injection, and target processing with Deno.bundle.
 */

import { join, } from "@std/path";
import { updateProjectVersion, } from "../tools/version.ts";
import {
  cleanTarget,
  copyStaticFiles,
  ensureDirForFile,
  listAssetsForCache,
  resolveWithBase,
  applyDefines
} from "../tools/paths.ts";

import { validateTargetConfig, } from "../tools/validate.ts";
import { resolveTargetOrder, } from "../tools/targets.ts";

import { buildBundleOptions, } from "./bundle.ts";
import type {
  DenoBuildOptions,
  DenoBuildResult,
  DenoBundleGlobalConfig,
  DenoBundleTargetConfig,
} from "../tools/interfaces.ts";

/**
 * Processes the compilation of a specific target using the Deno.bundle engine.
 *
 * Executed steps:
 * 1. Configuration consistency validation
 * 2. Pre-cleanup of output directories (clean)
 * 3. Copying of static files and HTML templates
 * 4. Preparation of compile-time definitions (defines)
 * 5. Invocation of the native `Deno.bundle` API
 * 6. Memory variable injection and disk writing
 *
 * @param targetName Target identifier name (e.g., "ui")
 * @param config Target configuration object
 * @param appVersion Current application semantic version
 * @param listAssetsFn Optional function to list generated assets for Service Worker cache
 * @returns Detailed target compilation result
 *
 * @example
 * ```typescript
 * const result = await processBundleTarget("ui", config, "0.3.5");
 * ```
 */
export async function processBundleTarget(
  targetName: string,
  config: DenoBundleTargetConfig,
  appVersion: string,
  listAssetsFn?: (distDir: string,) => Promise<string[]>,
  baseDir: string = ".",
  defineVersionString?: string,
): Promise<DenoBuildResult> {
  const resolvedConfig: DenoBundleTargetConfig = {
    ...config,
    srcdir: resolveWithBase(config.srcdir, baseDir,),
    distdir: resolveWithBase(config.distdir, baseDir,),
  };

  validateTargetConfig(targetName, resolvedConfig,);

  console.log(`\n${"=".repeat(60,)}`,);
  console.log(`🎯 PROCESSING TARGET: ${targetName.toUpperCase()}`,);
  console.log(`${"=".repeat(60,)}`,);

  // 1. Clean output directory
  if (resolvedConfig.clean) {
    if (resolvedConfig.distdir) {
      await cleanTarget(resolvedConfig.distdir, resolvedConfig.clean,);
    } else {
      console.warn(
        `⚠️ 'clean' configured but 'distdir' missing. Skipping cleanup.`,
      );
    }
  }

  // 2. Copy static files
  await copyStaticFiles(
    resolvedConfig,
    appVersion,
    baseDir,
    resolvedConfig.distdir,
  );

  // 3. Prepare defines
  // deno-lint-ignore no-explicit-any
  const defineVersionKey = defineVersionString || (resolvedConfig as any).defineVersionString || "__APP_VERSION__";
  const defines: Record<string, string> = {
    ...resolvedConfig.define,
    [defineVersionKey]: JSON.stringify(`v${appVersion}`,),
  };

  if (
    resolvedConfig.defineAssetsString &&
    resolvedConfig.defineAssetsString.trim() !== "" &&
    listAssetsFn &&
    resolvedConfig.distdir
  ) {
    const assets = await listAssetsFn(resolvedConfig.distdir,);
    defines[resolvedConfig.defineAssetsString] = JSON.stringify(assets,);
    console.log(`📋 ${assets.length} assets listed for define '${resolvedConfig.defineAssetsString}'`,);
  }

  // 4. Run bundle
  console.log(`🔨 Compiling with Deno.bundle...`,);
  const startTime = performance.now();
  const bundleOptions = buildBundleOptions(resolvedConfig,);
  const result = await Deno.bundle(bundleOptions,);

  // 5. Check for errors
  if (!result.success) {
    console.error("❌ Compilation errors:",);
    for (const error of result.errors) {
      const loc = error.location
        ? ` (${error.location.file}:${error.location.line}:${error.location.column})`
        : "";
      console.error(`   ${error.text}${loc}`,);
      for (const note of error.notes ?? []) {
        console.error(`      💡 ${note.text}`,);
      }
    }
    throw new Error(`Bundle failed for target [${targetName}]`,);
  }

  // 6. Display warnings (if any)
  for (const warning of result.warnings) {
    const loc = warning.location
      ? ` (${warning.location.file}:${warning.location.line}:${warning.location.column})`
      : "";
    console.warn(`   ⚠️ ${warning.text}${loc}`,);
  }

  // 7. Process generated files
  const outputFiles = result.outputFiles ?? [];
  const writtenPaths: string[] = [];

  if (outputFiles.length === 0) {
    console.warn(`   ⚠️ No files generated by bundle [${targetName}]`,);
    return {
      target: targetName,
      success: true,
      durationMs: Number((performance.now() - startTime).toFixed(0,),),
      outputFiles: [],
    };
  }

  const defineKeys = Object.keys(defines,);
  const hasDefines = defineKeys.length > 0;
  if (hasDefines) {
    console.log(
      `🔧 Injecting ${defineKeys.length} define(s): ${defineKeys.join(", ",)}`,
    );
  }

  for (const outputFile of outputFiles) {
    let content = outputFile.text();

    // 7.1 Inject globalName if IIFE and no native support (manual fallback)
    if (resolvedConfig.format === "iife" && resolvedConfig.globalName && !content.includes(`var ${resolvedConfig.globalName}`)) {
      content = `var ${resolvedConfig.globalName} = (function() {\nvar exports = {};\n${content}\nreturn exports;\n})();`;
    }

    // 7.2 Apply Defines
    if (hasDefines) {
      content = applyDefines(content, defines,);
    }

    // 7.3 Apply Banner (JS)
    if (resolvedConfig.banner?.js && (outputFile.path.endsWith(".js") || outputFile.path.endsWith(".mjs"))) {
      const banner = resolvedConfig.banner.js
        .replaceAll("__APP_VERSION__", appVersion)
        .replaceAll(defineVersionKey, appVersion);
      content = banner + "\n" + content;
    }

    // 7.4 Apply Footer (JS)
    if (resolvedConfig.footer?.js && (outputFile.path.endsWith(".js") || outputFile.path.endsWith(".mjs"))) {
      const footer = resolvedConfig.footer.js
        .replaceAll("__APP_VERSION__", appVersion)
        .replaceAll(defineVersionKey, appVersion);
      content = content + "\n" + footer;
    }

    // 7.5 Write to disk (unless write is explicitly false)
    if (resolvedConfig.write !== false) {
      await ensureDirForFile(outputFile.path,);
      await Deno.writeTextFile(outputFile.path, content,);
      writtenPaths.push(outputFile.path,);
      console.log(
        `   📄 ${outputFile.path} (${(content.length / 1024).toFixed(1,)}KB)`,
      );
    } else {
      writtenPaths.push(outputFile.path,);
      console.log(
        `   📦 [In-Memory] ${outputFile.path} (${(content.length / 1024).toFixed(1,)}KB)`,
      );
    }
  }

  const durationMs = Number((performance.now() - startTime).toFixed(0,),);
  console.log(
    `✅ [${targetName}] Build completed in ${durationMs}ms (${outputFiles.length} file(s))`,
  );

  return {
    target: targetName,
    success: true,
    durationMs,
    outputFiles: writtenPaths,
  };
}

/**
 * Programmatically executes compilation via Deno.bundle for configured targets.
 * Accepts a DenoBundleGlobalConfig object directly in memory or DenoBuildOptions.
 *
 * @param configOuOpcoes Memory DenoBundleGlobalConfig object or full execution options
 * @returns List of results obtained per target
 *
 * @example
 * ```typescript
 * const results = await denoBuild({
 *   config: {
 *     ui: { entryPoints: ["main.tsx"], distdir: "dist", srcdir: "src" }
 *   },
 *   targets: ["ui"],
 *   noversion: true
 * });
 * ```
 */
export async function denoBuild(
  opcoes: DenoBuildOptions,
): Promise<DenoBuildResult[]> {
  const configs = opcoes.config;
  const baseDir = opcoes.baseDir ?? ".";
  const denoJsoncPath = opcoes.denoJsoncPath ?? join(baseDir, "deno.jsonc",);

  // Strictly ensures that the execution order follows the declaration in the configuration
  const targetsToExecute = resolveTargetOrder(configs, opcoes.targets,);

  console.log(
    `📋 Build targets (safe CONFIG order): ${
      targetsToExecute.join(", ",) || "(none)"
    }`,
  );

  if (targetsToExecute.length === 0) {
    return [];
  }

  const finalVersion = await updateProjectVersion({
    denoJsonPath: denoJsoncPath,
    baseDir,
    noversion: opcoes.noversion ?? false,
    versionPaths: opcoes.versionPaths,
    forcepackagesversion: opcoes.forcepackagesversion,
    defineVersionString: opcoes.defineVersionString,
  },);

  const resultados: DenoBuildResult[] = [];

  for (const targetName of targetsToExecute) {
    const targetConfig = configs[targetName];
    if (!targetConfig) {
      console.warn(
        `⚠️ Target '${targetName}' not found in configuration. Skipping.`,
      );
      continue;
    }

    const listFn = targetConfig.defineAssetsString ? listAssetsForCache : undefined;
    const res = await processBundleTarget(
      targetName,
      targetConfig,
      finalVersion,
      listFn,
      baseDir,
      opcoes.defineVersionString,
    );
    resultados.push(res,);
  }

  return resultados;
}
