/**
 * @module @vanaware/buildit/docgen/reports
 * @description Report generation logic (API Surface and Coverage).
 */

import type { DocNode, } from "@deno/doc";
import type { SymbolIndex, DocgenResult, } from "./types.ts";

/**
 * Generates the _api-surface.md report (P0.2).
 */
export async function generateApiSurface(
  index: SymbolIndex,
  packageName: string,
  version: string,
): Promise<string> {
  let md = `# API Surface\n\n`;
  md += `> **Warning**: This file is automatically generated. Do not edit manually.\n`;
  md += `> Differences in this file between commits indicate changes in the public API.\n\n`;
  md += `Version: ${version}\n`;
  md += `Generated at: ${new Date().toISOString()}\n\n`;

  md += `## ${packageName}\n\n`;

  // Sort by file then kind then name
  const fileEntries = Array.from(index.byFile.entries());
  fileEntries.sort((a, b) => a[0].localeCompare(b[0]));

  for (const [fileUrl, entries] of fileEntries) {
    const fileName = entries[0]?.fileName ?? "Unknown";
    md += `### ${fileName}\n\n`;

    entries.sort((a, b) => {
      if (a.kind !== b.kind) return a.kind.localeCompare(b.kind);
      return a.name.localeCompare(b.name);
    });

    for (const entry of entries) {
      md += `- \`${entry.kind}\` \`${entry.name}\`\n`;
    }
    md += "\n";
  }

  // Calculate hash (simplified)
  const encoder = new TextEncoder();
  const data = encoder.encode(md);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const hashHex = hashArray.map(b => b.toString(16).padStart(2, "0")).join("");

  md = md.replace("API Surface\n\n", `API Surface\n\nContent Hash: \`${hashHex}\`\n\n`);

  return md;
}

/**
 * Generates the _coverage.md report (P0.3).
 */
export function generateCoverageReport(
  stats: DocgenResult["stats"],
  index: SymbolIndex,
  nodesByFile: Map<string, DocNode[]>,
): string {
  let md = `# Documentation Coverage\n\n`;

  md += `| Module | Symbols | Documented | Coverage |\n`;
  md += `|--------|----------|--------------|-----------|\n`;

  const rows: string[] = [];
  for (const [fileUrl, nodes] of nodesByFile.entries()) {
    const entries = index.byFile.get(fileUrl);
    if (!entries || entries.length === 0) continue;
    const fileName = entries[0]!.fileName;
    const total = nodes.length;
    const documented = nodes.filter(n => n.jsDoc?.doc).length;
    const percentage = total > 0 ? Math.round((documented / total) * 100) : 100;
    const status = percentage >= 90 ? "🟢" : percentage >= 70 ? "🟡" : percentage >= 50 ? "🟠" : "🔴";

    rows.push(`| ${fileName} | ${total} | ${documented} | ${status} ${percentage}% |`);
  }

  md += rows.join("\n") + "\n";
  md += `| **Total** | **${stats.coverage.symbolsTotal}** | **${stats.coverage.symbolsDocumented}** | **${getCoverageStatus(stats.coverage.percentage)} ${stats.coverage.percentage}%** |\n\n`;

  md += `## Undocumented Symbols\n\n`;
  for (const [fileUrl, nodes] of nodesByFile.entries()) {
    const entries = index.byFile.get(fileUrl);
    if (!entries || entries.length === 0) continue;
    const fileName = entries[0]!.fileName;
    const undocumented = nodes.filter(n => !n.jsDoc?.doc);
    if (undocumented.length > 0) {
      md += `- 🔴 \`${fileName}\` → ${undocumented.map(n => `\`${n.name}\``).join(", ")}\n`;
    }
  }

  return md;
}

function getCoverageStatus(percentage: number): string {
  if (percentage >= 90) return "🟢";
  if (percentage >= 70) return "🟡";
  if (percentage >= 50) return "🟠";
  return "🔴";
}
